// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/store/store.go
//
// Generated by this command:
//
//	mockgen -package=store -destination=./pkg/store/store_mock.go -source=./pkg/store/store.go Store
//

// Package store is a generated GoMock package.
package store

import (
	reflect "reflect"

	workerpool "github.com/absaoss/daggerpool/pkg/workerpool"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ClearJobSnapshot mocks base method.
func (m *MockStore) ClearJobSnapshot(arg0 workerpool.Job) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearJobSnapshot", arg0)
}

// ClearJobSnapshot indicates an expected call of ClearJobSnapshot.
func (mr *MockStoreMockRecorder) ClearJobSnapshot(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearJobSnapshot", reflect.TypeOf((*MockStore)(nil).ClearJobSnapshot), arg0)
}

// Get mocks base method.
func (m *MockStore) Get(key string) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStoreMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStore)(nil).Get), key)
}

// GetSnapshotInProgress mocks base method.
func (m *MockStore) GetSnapshotInProgress() map[string]*Snapshot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSnapshotInProgress")
	ret0, _ := ret[0].(map[string]*Snapshot)
	return ret0
}

// GetSnapshotInProgress indicates an expected call of GetSnapshotInProgress.
func (mr *MockStoreMockRecorder) GetSnapshotInProgress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSnapshotInProgress", reflect.TypeOf((*MockStore)(nil).GetSnapshotInProgress))
}

// Set mocks base method.
func (m *MockStore) Set(key string, value any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, value)
}

// Set indicates an expected call of Set.
func (mr *MockStoreMockRecorder) Set(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockStore)(nil).Set), key, value)
}

// SetJobSnapshot mocks base method.
func (m *MockStore) SetJobSnapshot(arg0 workerpool.Job, arg1 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetJobSnapshot", arg0, arg1)
}

// SetJobSnapshot indicates an expected call of SetJobSnapshot.
func (mr *MockStoreMockRecorder) SetJobSnapshot(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetJobSnapshot", reflect.TypeOf((*MockStore)(nil).SetJobSnapshot), arg0, arg1)
}
